driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
  region: us-east-1
  availability_zone: us-east-1c
  require_chef_omnibus: true
  security_group_ids: <%= ENV['SECURITY_GROUP_IDS'] %>
  associate_public_ip: true
  interface: dns

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04
    driver:
          name: vagrant

  - name: amazon
    driver:
      image_id: <%= ENV['AWS_IMAGE_ID'] %>
    transport:
      username: ec2-user
      ssh_key: ../ec2_keys/<%= ENV['AWS_SSH_KEY_ID'] %>.pem

suites:
  - name: default
    run_list:
      - recipe[jenkins::master]
      - recipe[aws-cookbook::default]

    attributes:
